apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: pod-delete-template
  namespace: argo
spec:
  entrypoint: delete-pod # We reference our first "template" here
  serviceAccountName: pod-delete-sa
  arguments:
    parameters:
      - name: falco-event
        value: "{}"
  templates:
    - name: delete-pod
      inputs:
        parameters:
          - name: falco-event
      container:
        image: devopps/kubernetes-response-engine-based-on-event-driven-workflow@sha256:22ee203a33fe88f0f99968daebdcea0ca52c8a3d6f7af4c823ed78ac15b7c5db
        env:
          - name: BODY
            value: "{{inputs.parameters.falco-event}}"
