falco:
  falcosidekick:
      enabled: true
      webui:
          enabled: true
      config:
          webhook:
              address: http://webhook-falco-eventsource-svc.argo-events.svc.cluster.local:12000/falco
              customHeaders: Source:falco
  fakeEventGenerator:
    enabled: false
  docker:
    enabled: false
  containerd:
      enabled: true
      socket: /run/k3s/containerd/containerd.sock
  falco:
    rulesFile:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml
      - /etc/falco/k8s_audit_rules.yaml
      - /etc/falco/rules.d/custom-rules.yaml
  customRules:
    custom-rules.yaml: |-
        - list: user_known_chmod_applications
          items: [hyperkube, kubelet, k3s-agent, k3s-server]
        - macro: user_known_contact_k8s_api_server_activities
          condition: >
            (container.image.repository in (docker.io/argoproj/argoexec)
             or k8s.ns.name in (k3os-system, argocd, argo, argo-events))
