falco:
    falcosidekick:
        enabled: true
        webui:
            enabled: true
        config:
            webhook:
                address: http://webhook-eventsource-svc.argo-events.svc.cluster.local:12000/falco
                customHeaders: Source:falco

